Repository XbyOrange/mercury-prismic, pull requests merged in 2019-10, with the labels that each got.

#6 Upgrade dependencies
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: dependencies

#7 Config method
  CHANGELOG.md
  README.md
  src/Prismic.js
  test/Prismic.spec.js
Labels: enhancement

#8 V1.2.0
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/Prismic.js
  test/Prismic.spec.js
Labels: dependencies, enhancement

#10 Configure eslint to disallow the use of undefined variable
  .eslintrc.json
  .gitignore
  test/Prismic.spec.js
  test/index.spec.js
Labels: quality

#12 Change url in runtime
  CHANGELOG.md
  src/Prismic.js
  test/Prismic.spec.js
Labels: enhancement

#13 V1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
  sonar-project.properties
  src/Prismic.js
  test/Prismic.spec.js
Labels: enhancement
